// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_jh985.Models;

namespace Mission06_jh985.Migrations
{
    [DbContext(typeof(MovieEntryContext))]
    partial class MovieEntryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_jh985.Models.MovieEntry", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Title");

                    b.ToTable("Response");

                    b.HasData(
                        new
                        {
                            Title = "The Proposal",
                            Category = "Romance",
                            Director = "Joseph B. Worthin",
                            Edited = true,
                            Lent = "David A Bednar",
                            Notes = "Best Movie created babe",
                            Rating = "PG-13",
                            Year = 1980
                        },
                        new
                        {
                            Title = "Harry Potter",
                            Category = "Fantasy",
                            Director = "JK Rowling",
                            Edited = false,
                            Lent = "Pooh Bear",
                            Notes = "pretty good movie babe",
                            Rating = "PG-13",
                            Year = 2007
                        },
                        new
                        {
                            Title = "Forever Strong",
                            Category = "Sports",
                            Director = "Kevin Holt",
                            Edited = true,
                            Lent = "Dee Dee Holt",
                            Notes = "Motivated me to win the state champtionship",
                            Rating = "R",
                            Year = 2013
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
